<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5f0d7db30e22a',
	'title' => 'General Options',
	'fields' => array(
		array(
			'key' => 'field_5f0d7db315ea8',
			'label' => 'Style & Layout',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f0d7db31625c',
			'label' => 'Default top slider image',
			'name' => 'mmh_bg',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'acfe_uploader' => 'wp',
			'acfe_thumbnail' => 0,
			'return_format' => 'id',
			'preview_size' => 'menu-50',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5f48f90235561',
			'label' => 'Default Title line color',
			'name' => 'hc_lico',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
		),
		array(
			'key' => 'field_5f4f3f7501a51',
			'label' => 'Default Button color',
			'name' => 'hc_btnco',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
		),
		array(
			'key' => 'field_5f33c18cc0e21',
			'label' => 'Show Sticky Header',
			'name' => 'hc_stick',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5f33c1bbc0e22',
			'label' => 'Sticky Header Background Color',
			'name' => 'hc_stickco',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
		),
		array(
			'key' => 'field_5f0d7db3166b7',
			'label' => 'Header Top Bar',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f0d7db315fca',
						'operator' => '!=',
						'value' => 'header-side-line',
					),
				),
				array(
					array(
						'field' => 'field_5f0d7db315fca',
						'operator' => '!=',
						'value' => 'header-side',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f47cfb920ec1',
			'label' => 'Top Bar BG Color',
			'name' => 'hc_tbbg',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
		),
		array(
			'acfe_flexible_advanced' => 0,
			'acfe_flexible_stylised_button' => 0,
			'acfe_flexible_hide_empty_message' => 0,
			'acfe_flexible_empty_message' => '',
			'acfe_flexible_disable_ajax_title' => 0,
			'acfe_flexible_layouts_thumbnails' => 0,
			'acfe_flexible_layouts_settings' => 0,
			'acfe_flexible_layouts_ajax' => 0,
			'acfe_flexible_layouts_templates' => 0,
			'acfe_flexible_layouts_previews' => 0,
			'acfe_flexible_layouts_placeholder' => 0,
			'acfe_flexible_title_edition' => 0,
			'acfe_flexible_clone' => 0,
			'acfe_flexible_copy_paste' => 0,
			'acfe_flexible_toggle' => 0,
			'acfe_flexible_close_button' => 0,
			'acfe_flexible_remove_add_button' => 0,
			'acfe_flexible_remove_duplicate_button' => 0,
			'acfe_flexible_remove_delete_button' => 0,
			'acfe_flexible_lock' => 0,
			'acfe_flexible_modal_edition' => 0,
			'acfe_flexible_modal' => array(
				'acfe_flexible_modal_enabled' => false,
				'acfe_flexible_modal_title' => false,
				'acfe_flexible_modal_col' => '4',
				'acfe_flexible_modal_categories' => false,
			),
			'acfe_flexible_layouts_state' => '',
			'acfe_flexible_layouts_remove_collapse' => 0,
			'key' => 'field_5f0d7db426e6b',
			'label' => 'Top bar - Elements',
			'name' => 'hc_tbe',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layouts' => array(
				'layout_5e6159e1187f0' => array(
					'key' => 'layout_5e6159e1187f0',
					'name' => 'hc_tbtx',
					'label' => 'Text',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f0d7db42c735',
							'label' => 'Text',
							'name' => 'hc_tbtext',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 3,
							'new_lines' => 'br',
							'acfe_textarea_code' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5e8ce1737fa90' => array(
					'key' => 'layout_5e8ce1737fa90',
					'name' => 'hc_tbmc',
					'label' => 'MiniCart',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f0d7db42c88b',
							'label' => 'Show icon My account',
							'name' => 'tbmc_my',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5e61f8c8f0d28' => array(
					'key' => 'layout_5e61f8c8f0d28',
					'name' => 'hc_tbse',
					'label' => 'Search Bar',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f0d7db42c8d4',
							'label' => 'Show Search',
							'name' => 'hc_tbsse',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5e61f94ff0d2b' => array(
					'key' => 'layout_5e61f94ff0d2b',
					'name' => 'hc_tbnav',
					'label' => 'Nav Menu',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f0d7db42c91d',
							'label' => 'Nav',
							'name' => 'hc_tbssnv',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5e615a747979e' => array(
					'key' => 'layout_5e615a747979e',
					'name' => 'hc_tbic',
					'label' => 'Icon link',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f0d7db42c966',
							'label' => 'Icon',
							'name' => 'hc_blici',
							'type' => 'font-awesome',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'icon_sets' => array(
								0 => 'fas',
								1 => 'far',
								2 => 'fab',
							),
							'custom_icon_set' => '',
							'default_label' => '',
							'default_value' => '',
							'save_format' => 'element',
							'allow_null' => 0,
							'show_preview' => 1,
							'enqueue_fa' => 0,
							'fa_live_preview' => '',
							'choices' => array(
							),
						),
						array(
							'key' => 'field_5f0d9d4162af4',
							'label' => 'Icon color',
							'name' => 'hc_tbicol',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
						),
						array(
							'key' => 'field_5f0d7db42c9ae',
							'label' => 'Icon Image',
							'name' => 'hc_tbicim',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'acfe_uploader' => 'wp',
							'acfe_thumbnail' => 0,
							'return_format' => 'id',
							'preview_size' => 'menu-50',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5f0d7db42c9f7',
							'label' => 'Text',
							'name' => 'hc_tbictx',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f0d7db42ca3f',
							'label' => 'Link Type',
							'name' => 'hc_tbiclty',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'free-link' => 'Free Link',
								'popup-form' => 'PopUp Form',
								'page' => 'Page',
								'popup-video' => 'PopUp Video',
							),
							'default_value' => false,
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5f0d7db42ca89',
							'label' => 'Form',
							'name' => 'hc_tbicfo',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5f0d7db42ca3f',
										'operator' => '==',
										'value' => 'popup-form',
									),
								),
							),
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'post_type' => array(
								0 => 'wpcf7_contact_form',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'id',
							'save_custom' => 0,
							'save_post_status' => 'publish',
							'acfe_bidirectional' => array(
								'acfe_bidirectional_enabled' => '0',
							),
							'ui' => 1,
						),
						array(
							'key' => 'field_5f0d7db42cad2',
							'label' => 'Page',
							'name' => 'hc_tbicpg',
							'type' => 'page_link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5f0d7db42ca3f',
										'operator' => '==',
										'value' => 'page',
									),
								),
							),
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'post_type' => array(
								0 => 'post',
								1 => 'page',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'allow_archives' => 1,
							'multiple' => 0,
						),
						array(
							'key' => 'field_5f0d7db42cb1b',
							'label' => 'Link',
							'name' => 'hc_tbiclk',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5f0d7db42ca3f',
										'operator' => '==',
										'value' => 'free-link',
									),
								),
								array(
									array(
										'field' => 'field_5f0d7db42ca3f',
										'operator' => '==',
										'value' => 'popup-video',
									),
								),
							),
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
			),
			'button_label' => 'Add Row',
			'min' => '',
			'max' => '',
		),
		array(
			'key' => 'field_5f0d7db4948b3',
			'label' => 'Footer',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f0d7db5d6597',
			'label' => 'Show mobile fixed bar',
			'name' => 'foo_fix',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'acfe_flexible_advanced' => 0,
			'acfe_flexible_stylised_button' => 0,
			'acfe_flexible_hide_empty_message' => 0,
			'acfe_flexible_empty_message' => '',
			'acfe_flexible_disable_ajax_title' => 0,
			'acfe_flexible_layouts_thumbnails' => 0,
			'acfe_flexible_layouts_settings' => 0,
			'acfe_flexible_layouts_ajax' => 0,
			'acfe_flexible_layouts_templates' => 0,
			'acfe_flexible_layouts_previews' => 0,
			'acfe_flexible_layouts_placeholder' => 0,
			'acfe_flexible_title_edition' => 0,
			'acfe_flexible_clone' => 0,
			'acfe_flexible_copy_paste' => 0,
			'acfe_flexible_toggle' => 0,
			'acfe_flexible_close_button' => 0,
			'acfe_flexible_remove_add_button' => 0,
			'acfe_flexible_remove_duplicate_button' => 0,
			'acfe_flexible_remove_delete_button' => 0,
			'acfe_flexible_lock' => 0,
			'acfe_flexible_modal_edition' => 0,
			'acfe_flexible_modal' => array(
				'acfe_flexible_modal_enabled' => false,
				'acfe_flexible_modal_title' => false,
				'acfe_flexible_modal_col' => '4',
				'acfe_flexible_modal_categories' => false,
			),
			'acfe_flexible_layouts_state' => '',
			'acfe_flexible_layouts_remove_collapse' => 0,
			'key' => 'field_5f0d7db4a1010',
			'label' => 'Footer Content Elements',
			'name' => 'foo_flex',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layouts' => array(
				'layout_5cf623csdde12' => array(
					'key' => 'layout_5cf623csdde12',
					'name' => 'f_fcon',
					'label' => 'Full content',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f0d7db4a5f73',
							'label' => 'Order on mobile',
							'name' => 'fctor',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'field_5f0d7db4a5fc6',
							'label' => 'Block Width',
							'name' => 'fcw',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'col-md-12' => 'full width',
								'col-sm-6 col-md-1' => '8.33%',
								'col-sm-6 col-md-2' => '16.67%',
								'col-sm-6 col-md-20' => '20%',
								'col-sm-6 col-md-3' => '25%',
								'col-sm-6 col-md-4' => '33.33%',
								'col-sm-6 col-md-5' => '42.85%',
								'col-sm-6 col-md-6' => '50%',
								'col-sm-6 col-md-7' => '57.15%',
								'col-sm-6 col-md-8' => '66.67%',
								'col-sm-6 col-md-9' => '75%',
								'col-sm-6 col-md-10' => '83.33%',
								'col-sm-6 col-md-11' => '91.67%',
							),
							'default_value' => false,
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5f0d7db4a6015',
							'label' => 'Mobile layout',
							'name' => 'fcwm',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'col-xs-12' => '100%',
								'col-xs-6' => '50%',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5f0d7db4a605f',
							'label' => 'Hide On Mobile',
							'name' => 'fcmh',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5f0d7db4a60aa',
							'label' => 'Title',
							'name' => 'fcti',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f0d7db4a60f4',
							'label' => 'Title - font size',
							'name' => 'fctis',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'field_5f0d7db4a613c',
							'label' => 'Title color',
							'name' => 'fctic',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
						),
						array(
							'key' => 'field_5f0d7db4a6185',
							'label' => 'Content',
							'name' => 'fctx',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5e6e21f8f4073' => array(
					'key' => 'layout_5e6e21f8f4073',
					'name' => 'f_map',
					'label' => 'Map',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f0d7db4a61ce',
							'label' => 'Order on mobile',
							'name' => 'mpor',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'field_5f0d7db4a6218',
							'label' => 'Block Width',
							'name' => 'mpw',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'col-md-12' => 'full width',
								'col-sm-6 col-md-1' => '8.33%',
								'col-sm-6 col-md-2' => '16.67%',
								'col-sm-6 col-md-20' => '20%',
								'col-sm-6 col-md-3' => '25%',
								'col-sm-6 col-md-4' => '33.33%',
								'col-sm-6 col-md-5' => '42.85%',
								'col-sm-6 col-md-6' => '50%',
								'col-sm-6 col-md-7' => '57.15%',
								'col-sm-6 col-md-8' => '66.67%',
								'col-sm-6 col-md-9' => '75%',
								'col-sm-6 col-md-10' => '83.33%',
								'col-sm-6 col-md-11' => '91.67%',
							),
							'default_value' => false,
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5f0d7db4a6261',
							'label' => 'Mobile layout',
							'name' => 'mpwm',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'col-xs-12' => '100%',
								'col-xs-6' => '50%',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5f0d7db4a62a9',
							'label' => 'Hide On Mobile',
							'name' => 'mpmh',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5f0d7db4a62f1',
							'label' => 'Title',
							'name' => 'mpti',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f0d7db4a6339',
							'label' => 'SubTitle',
							'name' => 'mpst',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f0d7db4a6382',
							'label' => 'Title - font size',
							'name' => 'mptis',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'field_5f0d7db4a63cb',
							'label' => 'Title color',
							'name' => 'mptic',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
						),
						array(
							'key' => 'field_5f0d7db4a6414',
							'label' => 'SubTitle color',
							'name' => 'mpstc',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
						),
						array(
							'key' => 'field_5f0d7db4a645d',
							'label' => 'Content',
							'name' => 'mp',
							'type' => 'google_map',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'center_lat' => '',
							'center_lng' => '',
							'zoom' => '',
							'height' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5cf623c2s332' => array(
					'key' => 'layout_5cf623c2s332',
					'name' => 'f_se',
					'label' => 'Search bar',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f0d7db4a64a7',
							'label' => 'Order on mobile',
							'name' => 'seor',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f0d7db4a64ef',
							'label' => 'Block Width',
							'name' => 'sew',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'col-md-12' => 'full width',
								'col-sm-6 col-md-1' => '8.33%',
								'col-sm-6 col-md-2' => '16.67%',
								'col-sm-6 col-md-20' => '20%',
								'col-sm-6 col-md-3' => '25%',
								'col-sm-6 col-md-4' => '33.33%',
								'col-sm-6 col-md-5' => '42.85%',
								'col-sm-6 col-md-6' => '50%',
								'col-sm-6 col-md-7' => '57.15%',
								'col-sm-6 col-md-8' => '66.67%',
								'col-sm-6 col-md-9' => '75%',
								'col-sm-6 col-md-10' => '83.33%',
								'col-sm-6 col-md-11' => '91.67%',
							),
							'default_value' => false,
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5f0d7db4a6537',
							'label' => 'Mobile layout',
							'name' => 'sewm',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'col-xs-12' => '100%',
								'col-xs-6' => '50%',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5f0d7db4a6580',
							'label' => 'Hide On Mobile',
							'name' => 'sewmh',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5f0d7db4a65ca',
							'label' => 'Show search bar',
							'name' => 'sesh',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5cf62sadaer4232' => array(
					'key' => 'layout_5cf62sadaer4232',
					'name' => 'f_icl',
					'label' => 'Icon list',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f0d7db4a6612',
							'label' => 'Order on mobile',
							'name' => 'iclor',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'field_5f0d7db4a665b',
							'label' => 'Block Width',
							'name' => 'iclw',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'col-md-12' => 'full width',
								'col-sm-6 col-md-1' => '8.33%',
								'col-sm-6 col-md-2' => '16.67%',
								'col-sm-6 col-md-20' => '20%',
								'col-sm-6 col-md-3' => '25%',
								'col-sm-6 col-md-4' => '33.33%',
								'col-sm-6 col-md-5' => '42.85%',
								'col-sm-6 col-md-6' => '50%',
								'col-sm-6 col-md-7' => '57.15%',
								'col-sm-6 col-md-8' => '66.67%',
								'col-sm-6 col-md-9' => '75%',
								'col-sm-6 col-md-10' => '83.33%',
								'col-sm-6 col-md-11' => '91.67%',
							),
							'default_value' => false,
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5f0d7db4a66a3',
							'label' => 'Mobile layout',
							'name' => 'iclwm',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'col-xs-12' => '100%',
								'col-xs-6' => '50%',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5f0d7db4a66f0',
							'label' => 'Hide On Mobile',
							'name' => 'iclmh',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5f0d7db4a6738',
							'label' => 'Title',
							'name' => 'iclti',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f0d7db4a6781',
							'label' => 'Title - font size',
							'name' => 'icltis',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'field_5f0d7db4a67c9',
							'label' => 'Title color',
							'name' => 'icltic',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
						),
						array(
							'key' => 'field_5f0d7db4a6812',
							'label' => 'List',
							'name' => 'icll',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'acfe_repeater_stylised_button' => 0,
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5f0d7db550692',
									'label' => 'Icon',
									'name' => 'ico',
									'type' => 'font-awesome',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'icon_sets' => array(
										0 => 'fas',
										1 => 'far',
										2 => 'fal',
										3 => 'fab',
									),
									'custom_icon_set' => '',
									'default_label' => '',
									'default_value' => '',
									'save_format' => 'element',
									'allow_null' => 1,
									'show_preview' => 1,
									'enqueue_fa' => 0,
									'fa_live_preview' => '',
									'choices' => array(
									),
								),
								array(
									'key' => 'field_5f0d7db5506eb',
									'label' => 'Text',
									'name' => 'txt',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5f0d7db55073f',
									'label' => 'Link',
									'name' => 'lk',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5d1072sw39' => array(
					'key' => 'layout_5d1072sw39',
					'name' => 'f_nav',
					'label' => 'Footer Nav',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f0d7db5629ab',
							'label' => 'Order on mobile',
							'name' => 'fnavor',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'field_5f0d7db567ac3',
							'label' => 'Block Width',
							'name' => 'fnaw',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'col-md-12' => 'full width',
								'col-sm-6 col-md-1' => '8.33%',
								'col-sm-6 col-md-2' => '16.67%',
								'col-sm-6 col-md-20' => '20%',
								'col-sm-6 col-md-3' => '25%',
								'col-sm-6 col-md-4' => '33.33%',
								'col-sm-6 col-md-5' => '42.85%',
								'col-sm-6 col-md-6' => '50%',
								'col-sm-6 col-md-7' => '57.15%',
								'col-sm-6 col-md-8' => '66.67%',
								'col-sm-6 col-md-9' => '75%',
								'col-sm-6 col-md-10' => '83.33%',
								'col-sm-6 col-md-11' => '91.67%',
							),
							'default_value' => false,
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5f0d7db56cf46',
							'label' => 'Mobile layout',
							'name' => 'fnawm',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'col-xs-12' => '100%',
								'col-xs-6' => '50%',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5f0d7db57235a',
							'label' => 'Hide On Mobile',
							'name' => 'fnahm',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5f0d7db577464',
							'label' => 'Split in columns',
							'name' => 'fnavc',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => 1,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 1,
							'max' => 5,
							'step' => 1,
						),
						array(
							'key' => 'field_5f0d7db57c7b2',
							'label' => 'Title',
							'name' => 'fnati',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f0d7db581b0a',
							'label' => 'Title - font size',
							'name' => 'fnatis',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'field_5f0d7db587627',
							'label' => 'Title color',
							'name' => 'fnatic',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
						),
						array(
							'key' => 'field_5f0d7db58ca3b',
							'label' => 'Choose nav',
							'name' => 'fnav',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'footer-nav-1' => 'Footer nav 1',
								'footer-nav-2' => 'Footer nav 2',
								'footer-nav-3' => 'Footer nav 3',
							),
							'default_value' => false,
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5cf62sw2d333' => array(
					'key' => 'layout_5cf62sw2d333',
					'name' => 'f_sl',
					'label' => 'Social links',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f0d7db591d2f',
							'label' => 'Order on mobile',
							'name' => 'sltor',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'field_5f0d7db59637f',
							'label' => 'Block Width',
							'name' => 'slw',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'col-md-12' => 'full width',
								'col-sm-6 col-md-1' => '8.33%',
								'col-sm-6 col-md-2' => '16.67%',
								'col-sm-6 col-md-20' => '20%',
								'col-sm-6 col-md-3' => '25%',
								'col-sm-6 col-md-4' => '33.33%',
								'col-sm-6 col-md-5' => '42.85%',
								'col-sm-6 col-md-6' => '50%',
								'col-sm-6 col-md-7' => '57.15%',
								'col-sm-6 col-md-8' => '66.67%',
								'col-sm-6 col-md-9' => '75%',
								'col-sm-6 col-md-10' => '83.33%',
								'col-sm-6 col-md-11' => '91.67%',
							),
							'default_value' => false,
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5f0d7db59a8ee',
							'label' => 'Mobile layout',
							'name' => 'slmw',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'col-xs-12' => '100%',
								'col-xs-6' => '50%',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5f0d7db59e787',
							'label' => 'Hide On Mobile',
							'name' => 'slmh',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5f0d7db5a33c6',
							'label' => 'Title',
							'name' => 'slti',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f0d7db5a8241',
							'label' => 'Title - font size',
							'name' => 'sltis',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'field_5f0d7db5ac7be',
							'label' => 'Title color',
							'name' => 'sltic',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
						),
						array(
							'key' => 'field_5f0d7db5b0ede',
							'label' => 'Footer social links',
							'name' => 'slr',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'acfe_repeater_stylised_button' => 0,
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5f0d7db5b5d3c',
									'label' => 'Icon',
									'name' => 'ico',
									'type' => 'font-awesome',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'icon_sets' => array(
										0 => 'fas',
										1 => 'far',
										2 => 'fal',
										3 => 'fab',
									),
									'custom_icon_set' => '',
									'default_label' => '',
									'default_value' => '',
									'save_format' => 'element',
									'allow_null' => 0,
									'show_preview' => 1,
									'enqueue_fa' => 0,
									'fa_live_preview' => '',
									'choices' => array(
									),
								),
								array(
									'key' => 'field_5f0d7db5b5d8c',
									'label' => 'Link',
									'name' => 'lk',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5f0d7db5b5dd9',
									'label' => 'Text',
									'name' => 'txt',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5f0d7db5b5e21',
									'label' => 'Color',
									'name' => 'col',
									'type' => 'color_picker',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
			),
			'button_label' => 'Add new block',
			'min' => '',
			'max' => '',
		),
		array(
			'key' => 'field_5f153e86a2aaa',
			'label' => 'Footer mobile fixed bar',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f0d7db5d6597',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f0d7db5db525',
			'label' => 'Show search button',
			'name' => 'foo_fse',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5f0d7db5e01db',
			'label' => 'Show Page link button',
			'name' => 'foo_fpls',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5f0d7db5e3ecb',
			'label' => 'Show Free link button',
			'name' => 'foo_flks',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5f0d7db5e7bb5',
			'label' => 'Show form popup button',
			'name' => 'foo_fpos',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5f0d7db5eb076',
			'label' => 'Link button Icon',
			'name' => 'foo_flki',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dsksn6ggg33',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fal',
				3 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '',
			'default_value' => '',
			'save_format' => 'element',
			'allow_null' => 1,
			'show_preview' => 1,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5f0d7db5ed647',
			'label' => 'Link btn text',
			'name' => 'foo_flkb',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dsksn6ggg33',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f0d7db5f011e',
			'label' => 'Link to',
			'name' => 'foo_flkp',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dsksn6ggg33',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f0d7db609136',
			'label' => 'Free link button Icon',
			'name' => 'foo_ffli',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dsksn6wd3dd3',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fal',
				3 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '',
			'default_value' => '',
			'save_format' => 'element',
			'allow_null' => 1,
			'show_preview' => 1,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5f0d7db60caed',
			'label' => 'Free link button text',
			'name' => 'foo_fflb',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dsksn6wd3dd3',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f0d7db60fe96',
			'label' => 'Free link button to',
			'name' => 'foo_fflp',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dsksn6wd3dd3',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f0d7db6129d9',
			'label' => 'Popup form Icon',
			'name' => 'foo_ffoi',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjj2sd33',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fal',
				3 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '',
			'default_value' => '',
			'save_format' => 'element',
			'allow_null' => 1,
			'show_preview' => 1,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5f0d7db614de1',
			'label' => 'Popup form text',
			'name' => 'foo_ffob',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjj2sd33',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f0d7db61702e',
			'label' => 'Choose Form',
			'name' => 'foo_ffid',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjj2sd33',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'post_type' => array(
				0 => 'wpcf7_contact_form',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'allow_custom' => 0,
			'save_post_status' => 'publish',
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'ui' => 1,
		),
		array(
			'key' => 'field_5f0d7db61974c',
			'label' => 'Title',
			'name' => 'foo_ffti',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjj2sd33',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f0d7db61b835',
			'label' => 'Subtitle',
			'name' => 'foo_ffst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjj2sd33',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f0d7db61deff',
			'label' => 'WooCommerce',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f0d7db62002f',
			'label' => 'MiniCart position',
			'name' => 'mcart_po',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'mc_nav' => 'In Menu',
				'mc_hcbr' => 'Side of logo (Classic header only)',
				'mc_tb' => 'In Top Bar',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5f0d7db6224f6',
			'label' => 'MiniCart Icon color',
			'name' => 'mcart_co',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e8cde747fa8c',
						'operator' => '==',
						'value' => 'mc_nav',
					),
				),
				array(
					array(
						'field' => 'field_5e8cde747fa8c',
						'operator' => '==',
						'value' => 'mc_hcbr',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
		),
		array(
			'key' => 'field_5f0d7db62470b',
			'label' => 'MiniCart Icon size',
			'name' => 'mcart_sz',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e8cde747fa8c',
						'operator' => '==',
						'value' => 'mc_nav',
					),
				),
				array(
					array(
						'field' => 'field_5e8cde747fa8c',
						'operator' => '==',
						'value' => 'mc_hcbr',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5f0d7db6269df',
			'label' => 'MiniCart Icon side',
			'name' => 'mcart_sd',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e8cde747fa8c',
						'operator' => '==',
						'value' => 'mc_nav',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'mc_snav' => 'Close to nav items',
				'mc_onav' => 'Oposite to nav items',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5f0d7db628b00',
			'label' => 'Show icon search',
			'name' => 'mcart_ise',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e8cde747fa8c',
						'operator' => '==',
						'value' => 'mc_nav',
					),
				),
				array(
					array(
						'field' => 'field_5e8cde747fa8c',
						'operator' => '==',
						'value' => 'mc_hcbr',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5f0d7db62ab3f',
			'label' => 'Show icon My account',
			'name' => 'mcart_ima',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e8cde747fa8c',
						'operator' => '==',
						'value' => 'mc_nav',
					),
				),
				array(
					array(
						'field' => 'field_5e8cde747fa8c',
						'operator' => '==',
						'value' => 'mc_hcbr',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5f0d7db62d0dc',
			'label' => 'Shop page',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f0d7db62f72d',
			'label' => 'Shop top slider image',
			'name' => 'sho_mhbg',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'acfe_uploader' => 'wp',
			'acfe_thumbnail' => 0,
			'return_format' => 'id',
			'preview_size' => 'menu-50',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5f0d7db6324ef',
			'label' => 'Change shop main title',
			'name' => 'sho_mti',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f0d7db635751',
			'label' => 'Change sub-title',
			'name' => 'sho_msti',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f0d7db6388d4',
			'label' => 'Shop intro',
			'name' => 'sho_int',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 5,
			'new_lines' => 'br',
			'acfe_textarea_code' => 0,
		),
		array(
			'key' => 'field_5f0d7db63bd84',
			'label' => 'Categories Title',
			'name' => 'sho_cti',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f0d7db63f561',
			'label' => 'Categories SubTitle',
			'name' => 'sho_csti',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f0d7db642a27',
			'label' => 'Products Title',
			'name' => 'sho_pti',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f0d7db645a07',
			'label' => 'Products SubTitle',
			'name' => 'sho_psti',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f1fce2338911',
			'label' => 'Product Category page',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f1fce3b38912',
			'label' => 'Default Banner BG',
			'name' => 'pc_debn',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'acfe_uploader' => 'wp',
			'acfe_thumbnail' => 0,
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5f21d14221504',
			'label' => 'Bottom form side image',
			'name' => 'pc_defoimg',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'acfe_uploader' => 'wp',
			'acfe_thumbnail' => 0,
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5f0d7db64ad8b',
			'label' => 'Product page',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f0d7db663d24',
			'label' => 'Related products title',
			'name' => 'pro_drelti',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f0d7db667e31',
			'label' => 'Related products Subtitle',
			'name' => 'pro_drelsti',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f0d7db6b4659',
			'label' => 'Site popups and Forms',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f0d7db6b966e',
			'label' => 'Page default form title',
			'name' => 'def_foti',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f0d7db6be600',
			'label' => 'Page default form subtitle',
			'name' => 'def_fosti',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f0d7db6c360e',
			'label' => 'Default form popup',
			'name' => 'def_fopop',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'post_type' => array(
				0 => 'wpcf7_contact_form',
			),
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'object',
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
		),
		array(
			'key' => 'field_5f0d7db6c8f9d',
			'label' => 'Footer default form bg',
			'name' => 'def_fobg',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'acfe_uploader' => 'wp',
			'acfe_thumbnail' => 0,
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5f0d7db6ce442',
			'label' => '404 page',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f0d7db6d3f75',
			'label' => 'Site codes',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f0d7db6d8198',
			'label' => 'Code in - head',
			'name' => 'site_hco',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'acfe_textarea_code' => 0,
		),
		array(
			'key' => 'field_5f0d7db6dcb13',
			'label' => 'Code in - footer',
			'name' => 'site_fco',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'acfe_textarea_code' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_permissions' => '',
	'acfe_form' => 0,
	'acfe_meta' => array(
		'acfcloneindex' => array(
			'acfe_meta_key' => '',
			'acfe_meta_value' => '',
		),
	),
	'acfe_note' => '',
	'modified' => 1603536453,
));

endif;