<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5f7c5237607f6',
	'title' => 'Grid / Slider Block',
	'fields' => array(
		array(
			'key' => 'field_5f7c52eedabf4',
			'label' => 'Element Settings',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f7c5315dabf5',
			'label' => 'Layout source',
			'name' => 'fg_src',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'manual' => 'Custom grid',
				'gallery' => 'Gallery Grid',
				'page' => 'Page grid',
				'product' => 'Product grid',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f7c57f2a156c',
			'label' => 'Layout type',
			'name' => 'fg_tp',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c5315dabf5',
						'operator' => '!=',
						'value' => 'page',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'box-layout' => 'Box layout',
				'vid-layout' => 'Video layout',
				'grid-layout' => 'Grid layout',
				'flex-layout' => 'Flex layout',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f7c5d7796a08',
			'label' => 'Boxes in row',
			'name' => 'fg_cu',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c57f2a156c',
						'operator' => '==',
						'value' => 'box-layout',
					),
				),
				array(
					array(
						'field' => 'field_5f7c57f2a156c',
						'operator' => '==',
						'value' => 'vid-layout',
					),
				),
				array(
					array(
						'field' => 'field_5f7c5315dabf5',
						'operator' => '==',
						'value' => 'page',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => 3,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 1,
			'max' => 8,
			'step' => 1,
		),
		array(
			'key' => 'field_5f7c5e2596a0b',
			'label' => 'Boxes in row - mobile',
			'name' => 'fg_cum',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c57f2a156c',
						'operator' => '==',
						'value' => 'box-layout',
					),
				),
				array(
					array(
						'field' => 'field_5f7c57f2a156c',
						'operator' => '==',
						'value' => 'vid-layout',
					),
				),
				array(
					array(
						'field' => 'field_5f7c5315dabf5',
						'operator' => '==',
						'value' => 'page',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 1,
			'max' => 3,
			'step' => 1,
		),
		array(
			'key' => 'field_5f7c605381a01',
			'label' => 'Show as Slider',
			'name' => 'fg_sl',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c57f2a156c',
						'operator' => '==',
						'value' => 'box-layout',
					),
				),
				array(
					array(
						'field' => 'field_5f7c57f2a156c',
						'operator' => '==',
						'value' => 'vid-layout',
					),
				),
				array(
					array(
						'field' => 'field_5f7c5315dabf5',
						'operator' => '==',
						'value' => 'page',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5f7c606e81a02',
			'label' => 'Show as Slider on mobile',
			'name' => 'fg_slm',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c57f2a156c',
						'operator' => '==',
						'value' => 'box-layout',
					),
				),
				array(
					array(
						'field' => 'field_5f7c57f2a156c',
						'operator' => '==',
						'value' => 'vid-layout',
					),
				),
				array(
					array(
						'field' => 'field_5f7c5315dabf5',
						'operator' => '==',
						'value' => 'page',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5f8e88f8acf71',
			'label' => 'Page grid',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c5315dabf5',
						'operator' => '==',
						'value' => 'page',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f8e893aacf72',
			'label' => 'Grid Style',
			'name' => 'fg_pgs',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'article-mix' => 'Articles masonry',
				'article-split' => 'Articles split',
				'article-hover' => 'Articles Hover effect',
				'article' => 'Articles',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f8e8971acf73',
			'label' => 'Image size',
			'name' => 'fg_pis',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'block-300' => 'Cut 300px',
				'portrait' => 'Portrait',
				'inside-post' => 'Cut 620x425',
				'product-500c' => 'Cut 500px',
				'gallery-800' => 'Cut 800x400',
				'menu-100' => 'Cut 100px',
				'clients-slider' => 'Resize 150x75',
				'article-400' => 'Cut 400x220',
				'full' => 'full size',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f8ea1f7e4a5a',
			'label' => 'Hide Date',
			'name' => 'fg_hda',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f8e893aacf72',
						'operator' => '==',
						'value' => 'article-mix',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5f8e8998acf74',
			'label' => 'Select Pages',
			'name' => 'fg_pgp',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'post_type' => array(
				0 => 'post',
				1 => 'page',
			),
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements' => array(
				0 => 'featured_image',
			),
			'min' => '',
			'max' => '',
			'return_format' => 'object',
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
		),
		array(
			'key' => 'field_5f8e89e9acf75',
			'label' => 'Image Gallery',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c5315dabf5',
						'operator' => '==',
						'value' => 'gallery',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f8e8a0eacf76',
			'label' => 'Flex Layout style',
			'name' => 'fg_igfl',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c57f2a156c',
						'operator' => '==',
						'value' => 'flex-layout',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'layout1' => 'layout1',
				'layout2' => 'layout2',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f8e8a50acf77',
			'label' => 'Image size',
			'name' => 'fg_igs',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'block-300' => 'Cut 300px',
				'portrait' => 'Portrait',
				'inside-post' => 'Cut 620x425',
				'product-500c' => 'Cut 500px',
				'gallery-800' => 'Cut 800x400',
				'menu-100' => 'Cut 100px',
				'clients-slider' => 'Resize 150x75',
				'article-400' => 'Cut 400x220',
				'full' => 'full size',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f8e8a70acf78',
			'label' => 'Disable Wrap',
			'name' => 'fg_nwp',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5f8e8a8facf79',
			'label' => 'Gallery',
			'name' => 'fg_ig',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'insert' => 'append',
			'library' => 'all',
			'min' => '',
			'max' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5f7c6439af119',
			'label' => 'Custom grid',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c5315dabf5',
						'operator' => '==',
						'value' => 'manual',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f7c6468af11a',
			'label' => 'Grid Style',
			'name' => 'fg_cgs',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'simple' => 'Simple',
				'features' => 'Features',
				'stories' => 'Clean Stories',
				'features_icon' => 'Icon Features',
				'features_clean' => 'Clean Features',
				'branches' => 'Branches',
				'contact_boxes' => 'Contact Boxes',
				'testimonials' => 'Testimonials',
				'projects' => 'Projects',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f7c64a4af11b',
			'label' => 'Image position with text',
			'name' => 'fg_cip',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'img_top' => 'Top',
				'img_bottom' => 'Bottom',
				'img_start' => 'Side first',
				'img_end' => 'Side end',
				'img_bg' => 'As Backgroung',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f7c64cbaf11c',
			'label' => 'Image size',
			'name' => 'fg_cis',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'block-300' => 'Cut 300px',
				'portrait' => 'Portrait',
				'inside-post' => 'Cut 620x425',
				'product-500c' => 'Cut 500px',
				'gallery-800' => 'Cut 800x400',
				'menu-100' => 'Cut 100px',
				'clients-slider' => 'Resize 150x75',
				'article-400' => 'Cut 400x220',
				'full' => 'full size',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f7cba370b793',
			'label' => 'Items Title Style',
			'name' => 'fg_ststy',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'simple' => 'simple',
				'line' => 'line',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f7c6725acc46',
			'label' => 'Image Box height',
			'name' => 'fg_cih',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c5315dabf5',
						'operator' => '==',
						'value' => 'manual',
					),
					array(
						'field' => 'field_5f7c57f2a156c',
						'operator' => '==',
						'value' => 'box-layout',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => 150,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => 10,
			'max' => 800,
			'step' => 1,
		),
		array(
			'key' => 'field_5f7c6789acc48',
			'label' => 'Overlap top margin',
			'name' => 'fg_oltm',
			'type' => 'number',
			'instructions' => 'Only use if first item under masthead',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c5315dabf5',
						'operator' => '==',
						'value' => 'manual',
					),
					array(
						'field' => 'field_5f7c57f2a156c',
						'operator' => '==',
						'value' => 'box-layout',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => 1,
		),
		array(
			'key' => 'field_5f7c681aacc49',
			'label' => 'Item padding',
			'name' => 'fg_ipa',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c5315dabf5',
						'operator' => '==',
						'value' => 'manual',
					),
					array(
						'field' => 'field_5f7c57f2a156c',
						'operator' => '==',
						'value' => 'box-layout',
					),
				),
			),
			'wrapper' => array(
				'width' => '16',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => 0,
			'max' => 200,
			'step' => 1,
		),
		array(
			'key' => 'field_5f7c684aacc4a',
			'label' => 'Item title size',
			'name' => 'fg_its',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c5315dabf5',
						'operator' => '==',
						'value' => 'manual',
					),
					array(
						'field' => 'field_5f7c57f2a156c',
						'operator' => '==',
						'value' => 'box-layout',
					),
				),
			),
			'wrapper' => array(
				'width' => '16',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => 10,
			'max' => 200,
			'step' => 1,
		),
		array(
			'key' => 'field_5f7c6883acc4b',
			'label' => 'Item subtitle size',
			'name' => 'fg_ists',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c5315dabf5',
						'operator' => '==',
						'value' => 'manual',
					),
					array(
						'field' => 'field_5f7c57f2a156c',
						'operator' => '==',
						'value' => 'box-layout',
					),
				),
			),
			'wrapper' => array(
				'width' => '16',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => 10,
			'max' => 200,
			'step' => 1,
		),
		array(
			'key' => 'field_5f7c68a2acc4c',
			'label' => 'Item title color',
			'name' => 'fg_itc',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c5315dabf5',
						'operator' => '==',
						'value' => 'manual',
					),
					array(
						'field' => 'field_5f7c57f2a156c',
						'operator' => '==',
						'value' => 'box-layout',
					),
				),
			),
			'wrapper' => array(
				'width' => '16',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
		),
		array(
			'key' => 'field_5f7c68c3acc4d',
			'label' => 'Item subtitle color',
			'name' => 'fg_istc',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c5315dabf5',
						'operator' => '==',
						'value' => 'manual',
					),
					array(
						'field' => 'field_5f7c57f2a156c',
						'operator' => '==',
						'value' => 'box-layout',
					),
				),
			),
			'wrapper' => array(
				'width' => '16',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
		),
		array(
			'key' => 'field_5f7c698d4a1f3',
			'label' => 'Grid Items',
			'name' => 'fg_gd',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c5315dabf5',
						'operator' => '==',
						'value' => 'manual',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'acfe_repeater_stylised_button' => 0,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5f7c69e04a1f4',
					'label' => 'Image',
					'name' => 'm_im',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f7c6468af11a',
								'operator' => '!=',
								'value' => 'stories',
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'acfe_uploader' => 'wp',
					'acfe_thumbnail' => 0,
					'return_format' => 'id',
					'preview_size' => 'menu-100',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5f7c6a404a1f5',
					'label' => 'OR Icon',
					'name' => 'm_icon',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f7c6468af11a',
								'operator' => '==',
								'value' => 'features_icon',
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'icon_sets' => array(
						0 => 'fas',
						1 => 'far',
						2 => 'fal',
						3 => 'fad',
						4 => 'fab',
					),
					'custom_icon_set' => '',
					'default_label' => '',
					'default_value' => '',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'key' => 'field_5f7c6a934a1f6',
					'label' => 'Title',
					'name' => 'm_t',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5f7c6aac4a1f7',
					'label' => 'Subtitle',
					'name' => 'm_st',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'br',
					'acfe_textarea_code' => 0,
				),
				array(
					'key' => 'field_5f7c6b024a1f8',
					'label' => 'Text',
					'name' => 'm_stxt',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f7c6468af11a',
								'operator' => '==',
								'value' => 'stories',
							),
						),
						array(
							array(
								'field' => 'field_5f7c6468af11a',
								'operator' => '==',
								'value' => 'testimonials',
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'br',
					'acfe_textarea_code' => 0,
				),
				array(
					'key' => 'field_5f7c8484233a3',
					'label' => 'Link type',
					'name' => 'm_lkt',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f7c57f2a156c',
								'operator' => '!=',
								'value' => 'vid-layout',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
						'free_link' => 'Free link',
						'form_popup' => 'Form Popup',
						'page_link' => 'Page link',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5f7c84c7233a4',
					'label' => 'Link',
					'name' => 'm_lk',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f7c57f2a156c',
								'operator' => '!=',
								'value' => 'vid-layout',
							),
							array(
								'field' => 'field_5f7c8484233a3',
								'operator' => '==',
								'value' => 'free_link',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5f7c84f7233a6',
					'label' => 'Page link',
					'name' => 'm_plk',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f7c57f2a156c',
								'operator' => '!=',
								'value' => 'vid-layout',
							),
							array(
								'field' => 'field_5f7c8484233a3',
								'operator' => '==',
								'value' => 'page_link',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'post_type' => array(
						0 => 'post',
						1 => 'page',
					),
					'taxonomy' => '',
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5f7c8528233a7',
					'label' => 'Form',
					'name' => 'm_flk',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f7c57f2a156c',
								'operator' => '!=',
								'value' => 'vid-layout',
							),
							array(
								'field' => 'field_5f7c8484233a3',
								'operator' => '==',
								'value' => 'form_popup',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'post_type' => array(
						0 => 'wpcf7_contact_form',
					),
					'taxonomy' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'save_custom' => 0,
					'save_post_status' => 'publish',
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'ui' => 1,
				),
				array(
					'key' => 'field_5f7c8560233a8',
					'label' => 'Video link',
					'name' => 'm_vlk',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f7c57f2a156c',
								'operator' => '==',
								'value' => 'vid-layout',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5f7c8582233a9',
					'label' => 'Video title',
					'name' => 'm_vt',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f7c57f2a156c',
								'operator' => '==',
								'value' => 'vid-layout',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5f7c85a99f12b',
					'label' => 'Bottom text',
					'name' => 'm_bot',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f7c6468af11a',
								'operator' => '==',
								'value' => 'contact_boxes',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5f7c85d49f12c',
					'label' => 'Button text',
					'name' => 'm_btnt',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5f7c861f9f12d',
					'label' => 'Open in new window',
					'name' => 'm_oinw',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f7c57f2a156c',
								'operator' => '!=',
								'value' => 'vid-layout',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_5f7c87809f12e',
					'label' => 'show overlay image',
					'name' => 'm_over',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f7c57f2a156c',
								'operator' => '!=',
								'value' => 'vid-layout',
							),
							array(
								'field' => 'field_5f7c6468af11a',
								'operator' => '==',
								'value' => 'simple',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_5f7c87ad9f130',
					'label' => 'Content position',
					'name' => 'm_cop',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f7c57f2a156c',
								'operator' => '!=',
								'value' => 'vid-layout',
							),
							array(
								'field' => 'field_5f7c6468af11a',
								'operator' => '==',
								'value' => 'simple',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
						'top' => 'top',
						'center' => 'center',
						'bottom' => 'bottom',
						'top_start' => 'top_start',
						'center_start' => 'center_start',
						'bottom_start' => 'bottom_start',
						'top_end' => 'top_end',
						'center_end' => 'center_end',
						'bottom_end' => 'bottom_end',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5f7c87d89f131',
					'label' => 'Title color',
					'name' => 'm_tic',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f7c57f2a156c',
								'operator' => '!=',
								'value' => 'vid-layout',
							),
							array(
								'field' => 'field_5f7c6468af11a',
								'operator' => '==',
								'value' => 'simple',
							),
						),
						array(
							array(
								'field' => 'field_5f7c6468af11a',
								'operator' => '==',
								'value' => 'features_icon',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
				),
				array(
					'key' => 'field_5f7c88549f134',
					'label' => 'SubTitle color',
					'name' => 'm_stc',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f7c57f2a156c',
								'operator' => '!=',
								'value' => 'vid-layout',
							),
							array(
								'field' => 'field_5f7c6468af11a',
								'operator' => '==',
								'value' => 'simple',
							),
						),
						array(
							array(
								'field' => 'field_5f7c6468af11a',
								'operator' => '==',
								'value' => 'features_icon',
							),
						),
						array(
							array(
								'field' => 'field_5f7c6468af11a',
								'operator' => '==',
								'value' => 'projects',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
				),
				array(
					'key' => 'field_5f7c88919f136',
					'label' => 'Item Background Color',
					'name' => 'm_ibg',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f7c57f2a156c',
								'operator' => '!=',
								'value' => 'vid-layout',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
				),
			),
		),
		array(
			'key' => 'field_5f7c62cd9abda',
			'label' => 'Element Button',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f7c60bf81a03',
			'label' => 'Bottom Button',
			'name' => 'fg_bbtn',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f7c60ea81a04',
			'label' => 'Button color',
			'name' => 'fg_bbtnc',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
		),
		array(
			'key' => 'field_5f7c60fd81a05',
			'label' => 'Button font',
			'name' => 'fg_bbtnf',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
		),
		array(
			'key' => 'field_5f7c611381a06',
			'label' => 'Button type',
			'name' => 'fg_bbtnt',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'link' => 'link',
				'page' => 'page',
				'form' => 'form',
				'category' => 'category',
				'video' => 'video',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f7c613c81a07',
			'label' => 'Button link',
			'name' => 'fg_bbtnl',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c611381a06',
						'operator' => '==',
						'value' => 'link',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f7c61c681a0a',
			'label' => 'Button video',
			'name' => 'fg_bbtnv',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c611381a06',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f7c619b81a09',
			'label' => 'Button page',
			'name' => 'fg_bbtnp',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c611381a06',
						'operator' => '==',
						'value' => 'page',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'post_type' => '',
			'taxonomy' => '',
			'allow_null' => 0,
			'allow_archives' => 1,
			'multiple' => 0,
		),
		array(
			'key' => 'field_5f7c61ee81a0b',
			'label' => 'Button category',
			'name' => 'fg_bbtnca',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c611381a06',
						'operator' => '==',
						'value' => 'category',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'taxonomy' => 'category',
			'field_type' => 'select',
			'allow_null' => 0,
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'multiple' => 0,
		),
		array(
			'key' => 'field_5f7c616881a08',
			'label' => 'Button form',
			'name' => 'fg_bbtnf',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f7c611381a06',
						'operator' => '==',
						'value' => 'form',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'post_type' => array(
				0 => 'wpcf7_contact_form',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'save_custom' => 0,
			'save_post_status' => 'publish',
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/acftkm-gridslide',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_permissions' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1603183269,
));

endif;